-- MySql
CREATE TABLE KmOrder(
	Id int NOT NULL AUTO_INCREMENT,
	CreatedOnUtc TIMESTAMP NOT NULL DEFAULT (UTC_TIMESTAMP),
    Data LONGTEXT NULL,
    Status VARCHAR(128) NOT NULL,
    KmOrderId VARCHAR(256) NOT NULL,
    KmUserId VARCHAR(256) NOT NULL,
    NopOrderId INT NOT NULL,
    Errors MEDIUMTEXT NULL,
    PRIMARY KEY (Id)
);